### PR TITLE
Play sounds (list on the app Mi Home)

### PR DESCRIPTION
**Pull request by Hamtar0**
Just use gateway.setSound(number)

numbers :
      - "0 - Police car 1"
      - "1 - Police car 2"
      - "2 - Accident"
      - "3 - Countdown"
      - "4 - Ghost"
      - "5 - Sniper rifle"
      - "6 - Battle"
      - "7 - Air raid"
      - "8 - Bark"
      - "10 - Doorbell"
      - "11 - Knock at a door"
      - "12 - Amuse"
      - "13 - Alarm clock"
      - "20 - MiMix"
      - "21 - Enthusiastic"
      - "22 - GuitarClassic"
      - "23 - IceWorldPiano"
      - "24 - LeisureTime"
      - "25 - ChildHood"
      - "26 - MorningStreamLiet"
      - "27 - MusicBox"
      - "28 - Orange"
      - "29 - Thinker"

And custom sounds recorded on the app starts with id 10001

### CODE REVIEW

**Comment by Hamtar0** [comment]
Glad that's ok for you, I'm not a pro dev... ;)

**Comment by marvinroger** [comment]
It's great, thanks! 😉

**Comment by KamilKafara** [comment]
How to add custom sounds ?

**Comment by marvinroger** [comment]
You have to add custom sounds on the Mi Home app

**Pull request merged**
